COMMON_SOURCES += mcf/priorityqueue.c \
		  mcf/network.c \
		  mcf/algorithm.c

COMMON_HEADERS += mcf/priorityqueue.h \
		  mcf/network.h \
		  mcf/algorithm.h

COMMON_OBJS := $(COMMON_SOURCES:.c=.o)
